from pathlib import Path

try:
    import torch
except Exception:  # pragma: no cover - optional dependency in lightweight deploys
    torch = None

SERVICE_ROOT = Path(__file__).resolve().parents[2]

# User-editable game configuration.
BOARD_SIZE = 4
WIN_LENGTH = BOARD_SIZE

# UI sizing.
GRID_CELL_SIZE = 96
CHESS_RADIUS = 28

EMPTY = 0
RED = 1
BLUE = -1
PLAYERS = (RED, BLUE)

# Backward-compatible alias used by older modules.
SIZE = BOARD_SIZE

# Reward shaping.
WIN_REWARD = 1.0
DRAW_REWARD = 0.0
STEP_REWARD = 0.0
INVALID_MOVE_PENALTY = -10.0

# Paths.
ROOT_DIR = SERVICE_ROOT
DATASET_DIR = ROOT_DIR / "datasets"
MODEL_DIR = ROOT_DIR / "models"

# Training defaults.
DEVICE = "cuda" if torch is not None and torch.cuda.is_available() else "cpu"
NETWORK_ARCH = "conv"
SEARCH_ENABLED = True
SEARCH_MAX_DEPTH = 3
SEARCH_TIME_LIMIT_MS = 0
SEARCH_USE_TRANSPOSITION = True
SEARCH_TOP_K_ORDERING = 8
SEARCH_NETWORK_GUIDANCE_WEIGHT = 0.15
SEARCH_HEURISTIC_WEIGHT = 1.0
SELF_PLAY_SEARCH_DEPTH = 2
INFERENCE_SEARCH_DEPTH = 3
EVAL_SEARCH_DEPTH = 2
LEARNING_RATE = 1e-3
GAMMA = 0.99
REPLAY_CAPACITY = 1_500_000
BATCH_SIZE = 500
TARGET_UPDATE_INTERVAL = 5
ONLINE_EPISODES = 3_000_00
OFFLINE_EPOCHS = 1000
CHECKPOINT_EPISODE_INTERVAL = 1000
CHECKPOINT_EPOCH_INTERVAL = 50
OPPONENT_NUMBER = 3
CHECKPOINT_MATCH_GAMES = 10
CHECKPOINT_BASE_SCORE = 1000.0
CHECKPOINT_SCORE_K = 32.0
EVAL_INTERVAL = 1000
OFFLINE_LOG_BATCH_INTERVAL = 30
ONLINE_LOG_EPISODE_INTERVAL = 50
EPSILON_START = 1.0
EPSILON_MIN = 0.05
EPSILON_DECAY = 0.997
OFFLINE_BATCH_SIZE = 250000

# Dataset defaults.
DATASET_CHUNK_SIZE = 20_000
DATASET_EPISODES = 10_000
DATASET_AUGMENT = True
DATASET_WRITE_COMPRESSED = True
INVALID_SAMPLING_PROB = 0.15
TACTICAL_POLICY_PROB = 0.65
RANDOM_POLICY_PROB = 0.35
NUM_DATASET_WORKERS = 1

# Evaluation defaults.
EVAL_GAMES = 10
RANDOM_SEED = 7
